import { Prompt } from "next/font/google";
import "./globals.css";
import 'bootstrap/dist/css/bootstrap.min.css';
import Navbar from "./navbar/navbar";  // นำเข้าคอมโพเนนต์ Navbar
import Nab from "./components/nab";  // นำเข้าคอมโพเนนต์ Nab
import BootstrapClient from "./components/BootstrapClient";
import Footer from "./components/footer";

const prompt = Prompt({ weight: ['400', '700'], subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={prompt.className}>
        <Navbar />  {/* เพิ่ม Navbar */}
        <Nab />  {/* ใช้คอมโพเนนต์ Nab */}
        {children}
        <BootstrapClient />
        <Footer />  {/* ยังคงใช้ Footer */}
      </body>
    </html>
  );
}
